samples/netcore2.2/SampleMvc2WebApp/Areas/Access/Controllers/RoleController.cs
using DynamicAuthorization.Mvc.Core;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SampleMvc2WebApp.Areas.Access.Models;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace SampleMvc2WebApp.Areas.Access.Controllers
{
    [Area("Access"), Authorize]
    [DisplayName("Role Management")]
    public class RoleController : Controller
    {
        private readonly IMvcControllerDiscovery _mvcControllerDiscovery;
        private readonly IRoleAccessStore _roleAccessStore;
        private readonly RoleManager<IdentityRole> _roleManager;

        public RoleController(
            IMvcControllerDiscovery mvcControllerDiscovery,
            IRoleAccessStore roleAccessStore,
            RoleManager<IdentityRole> roleManager
            )
        {
            _mvcControllerDiscovery = mvcControllerDiscovery;
            _roleManager = roleManager;
            _roleAccessStore = roleAccessStore;
        }

        // GET: Role
        [DisplayName("Role List")]
        public async Task<ActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();

            return View(roles);
        }

        [DisplayName("Create Role")]
        // GET: Role/Create
        public ActionResult Create()
        {
            var controllers = _mvcControllerDiscovery.GetControllers();
            ViewData["Controllers"] = controllers;

            return View();
        }

        // POST: Role/Create
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RoleViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Controllers"] = _mvcControllerDiscovery.GetControllers();
                return View(viewModel);
            }

            var role = new IdentityRole { Name = viewModel.Name };
            var result = await _roleManager.CreateAsync(role);

            if (!result.Succeeded)
            {
                foreach (var error in result.Errors)
                    ModelState.AddModelError("", error.Description);

                ViewData["Controllers"] = _mvcControllerDiscovery.GetControllers();
                return View(viewModel);
            }

            if (viewModel.SelectedControllers != null && viewModel.SelectedControllers.Any())
            {
                foreach (var controller in viewModel.SelectedControllers)
                    foreach (var action in controller.Actions)
                        action.ControllerId = controller.Id;

                var roleAccess = new RoleAccess
                {
                    Controllers = viewModel.SelectedControllers.ToList(),
                    RoleId = role.Id
                };
                await _roleAccessStore.AddRoleAccessAsync(roleAccess);
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: Role/Edit/5
        [DisplayName("Edit Role")]
        public async Task<ActionResult> Edit(string id)
        {
            ViewData["Controllers"] = _mvcControllerDiscovery.GetControllers();
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
                return NotFound();

            var accessList = await _roleAccessStore.GetRoleAccessAsync(role.Id);
            var viewModel = new RoleViewModel
            {
                Name = role.Name,
                SelectedControllers = accessList?.Controllers
            };

            return View(viewModel);
        }

        // POST: Role/Edit/5
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(string id, RoleViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Controllers"] = _mvcControllerDiscovery.GetControllers();
                return View(viewModel);
            }

            // Check role exit
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                ModelState.AddModelError("", "Role not found");
                ViewData["Controllers"] = _mvcControllerDiscovery.GetControllers();
                return View();
            }

            // Update role if role's name is changed
            if (role.Name != viewModel.Name)
            {
                role.Name = viewModel.Name;
                var result = await _roleManager.UpdateAsync(role);
                if (!result.Succeeded)
                {
                    foreach (var error in result.Errors)
                        ModelState.AddModelError("", error.Description);

                    ViewData["Controllers"] = _mvcControllerDiscovery.GetControllers();
                    return View(viewModel);
                }
            }

            // Update role access list
            if (viewModel.SelectedControllers != null && viewModel.SelectedControllers.Any())
            {
                foreach (var controller in viewModel.SelectedControllers)
                    foreach (var action in controller.Actions)
                        action.ControllerId = controller.Id;
            }

            var roleAccess = new RoleAccess
            {
                Controllers = viewModel.SelectedControllers?.ToList(),
                RoleId = role.Id
            };
            await _roleAccessStore.EditRoleAccessAsync(roleAccess);

            return RedirectToAction(nameof(Index));
        }

        // POST: Role/Delete/5
        [HttpDelete("role/{id}")]
        public async Task<ActionResult> Delete(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                ModelState.AddModelError("Error", "Role not found");
                return BadRequest(ModelState);
            }

            var result = await _roleManager.DeleteAsync(role);
            if (!result.Succeeded)
            {
                foreach (var error in result.Errors)
                    ModelState.AddModelError("Error", error.Description);

                return BadRequest(ModelState);
            }

            await _roleAccessStore.RemoveRoleAccessAsync(role.Id);

            return Ok(new { });
        }
    }
}

samples/netcore2.2/SampleMvc2WebApp/Areas/Access/Controllers/UserRoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SampleMvc2WebApp.Areas.Access.Models;
using SampleMvc2WebApp.Data;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace SampleMvc2WebApp.Areas.Access.Controllers
{
    [Area("Access"), Authorize]
    [DisplayName("User Role Management")]
    public class UserRoleController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<IdentityUser> _userManager;

        public UserRoleController(
            ApplicationDbContext dbContext,
            RoleManager<IdentityRole> roleManager,
            UserManager<IdentityUser> userManager
            )
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _dbContext = dbContext;
        }

        // GET: Access
        [DisplayName("User List")]
        public async Task<ActionResult> Index()
        {
            var query = await (
                    from user in _dbContext.Users
                    join ur in _dbContext.UserRoles on user.Id equals ur.UserId into userRoles
                    from userRole in userRoles.DefaultIfEmpty()
                    join rle in _dbContext.Roles on userRole.RoleId equals rle.Id into roles
                    from role in roles.DefaultIfEmpty()
                    select new { user, userRole, role }
                ).ToListAsync();

            var userList = new List<UserRoleViewModel>();
            foreach (var grp in query.GroupBy(q => q.user.Id))
            {
                var first = grp.First();
                userList.Add(new UserRoleViewModel
                {
                    UserId = first.user.Id,
                    UserName = first.user.UserName,
                    Roles = first.role != null ? grp.Select(g => g.role).Select(r => r.Name) : new List<string>()
                });
            }

            return View(userList);
        }

        // GET: Access/Edit
        [DisplayName("Edit User Roles")]
        public async Task<ActionResult> Edit(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
                return NotFound();

            var userRoles = await _userManager.GetRolesAsync(user);
            var userViewModel = new UserRoleViewModel
            {
                UserId = user.Id,
                UserName = user.UserName,
                Roles = userRoles
            };

            var roles = await _roleManager.Roles.ToListAsync();
            ViewData["Roles"] = roles;

            return View(userViewModel);
        }

        // POST: Access/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(UserRoleViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Roles"] = await _roleManager.Roles.ToListAsync();
                return View(viewModel);
            }

            var user = _dbContext.Users.Find(viewModel.UserId);
            if (user == null)
            {
                ModelState.AddModelError("", "User not found");
                ViewData["Roles"] = await _roleManager.Roles.ToListAsync();
                return View();
            }

            var userRoles = await _userManager.GetRolesAsync(user);
            await _userManager.RemoveFromRolesAsync(user, userRoles);
            await _userManager.AddToRolesAsync(user, viewModel.Roles);

            return RedirectToAction("Index");
        }
    }
}

samples/netcore2.2/SampleMvc2WebApp/Controllers/ProtectedOneController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel;

namespace SampleMvc2WebApp.Controllers
{
    [Authorize]
    [DisplayName("Protected section 1")]
    public class ProtectedOneController : Controller
    {
        [DisplayName("List")]
        public IActionResult Index()
        {
            return View();
        }

        [DisplayName("Detail")]
        public IActionResult Detail()
        {
            return View();
        }
    }
}

samples/netcore2.2/SampleMvc2WebApp/Controllers/ProtectedTwoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel;

namespace SampleMvc2WebApp.Controllers
{
    [Authorize]
    [DisplayName("Protected section 2")]
    public class ProtectedTwoController : Controller
    {
        [DisplayName("List")]
        public IActionResult Index()
        {
            return View();
        }

        [DisplayName("Detail")]
        public IActionResult Detail()
        {
            return View();
        }
    }
}

samples/netcore2.2/SampleMvc2WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SampleMvc2WebApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/js/jquery-bonsai/jquery.bonsai.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SampleMvc2WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Access
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <secure-content asp-area="Access" asp-controller="Role" asp-action="Index">
                                    <a class="dropdown-item text-dark" asp-area="Access" asp-controller="Role" asp-action="Index">Role List</a>
                                </secure-content>
                                <secure-content asp-area="Access" asp-controller="UserRole" asp-action="Index">
                                    <a class="dropdown-item text-dark" asp-area="Access" asp-controller="UserRole" asp-action="Index">User Role List</a>
                                </secure-content>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Protected Links
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <secure-content asp-area="" asp-controller="ProtectedOne" asp-action="Index">
                                    <a class="dropdown-item text-dark" asp-area="" asp-controller="ProtectedOne" asp-action="Index">Protected 1</a>
                                </secure-content>
                                <secure-content asp-area="" asp-controller="ProtectedOne" asp-action="Detail">
                                    <a class="dropdown-item text-dark" asp-area="" asp-controller="ProtectedOne" asp-action="Detail">Protected Detail 1</a>
                                </secure-content>
                                <secure-content asp-area="" asp-controller="ProtectedTwo" asp-action="Index">
                                    <a class="dropdown-item text-dark" asp-area="" asp-controller="ProtectedTwo" asp-action="Index">
                                        Protected 2
                                    </a>
                                </secure-content>
                                <secure-content asp-area="" asp-controller="ProtectedTwo" asp-action="Detail">
                                    <a class="dropdown-item text-dark" asp-area="" asp-controller="ProtectedTwo" asp-action="Detail">Protected Detail 2</a>
                                </secure-content>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SampleMvc2WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/jquery-qubit/jquery.qubit.js"></script>
    <script src="~/js/jquery-bonsai/jquery.bonsai.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>